options:
  auto-update: true

item-settings:
  crescent-hammer:
    damageable: true

messages:
  items:
    crescent-hammer:
      block-breaking: "&cYou cannot break blocks with this!"
      right-click-fail: "&cYou cannot dismantle this block!"