options:
  auto-update: true

item-settings:
  crescent-hammer:
    damageable: true

messages:
  items:
    crescent-hammer:
      block-breaking: "&cYou cannot break blocks with this!"
      dismantle-fail: "&cYou cannot dismantle this block!"
      rotate-fail: "&cYou cannot rotate this block!"
      