name: MoreTools
authors: [LinoxGH, ajan_12]
description: Adds more useful tools to Slimefun!
main: io.github.linoxgh.moretools.MoreTools
website: https://github.com/LinoxGH/MoreTools
depend: [Slimefun]
version: ${project.version}
api-version: 1.14

permissions:
  moretools.items.crescent-hammer.rotation-whitelist-bypass:
    description: "Lets the player to bypass block rotation whitelist."
    default: notop