name: MoreTools
authors: [LinoxGH, ajan_12]
description: Adds more useful tools to Slimefun!
main: io.github.linoxgh.moretools.MoreTools
website: https://github.com/LinoxGH/MoreTools
depend: [Slimefun]
ersion: ${project.version}
api-version: 1.14
